### ISSUE TITLE
Compatibility with Python 3.7+, "async" is a reserved keyword

### ISSUE THREAD

**Issue by adambielski** [podgorskiy/dlutils#1]
Importing the library fails with Python 3.7+ because a file can't be named async anymore:

```    import dlutils
  File "/home/adam/miniconda3/envs/alae/lib/python3.8/site-packages/dlutils/__init__.py", line 26
    from dlutils.async import *
                 ^
SyntaxError: invalid syntax
```

Simply renaming async.py to anything else solves the issue.

**Comment by podgorskiy** [comment]
I've renamed it and updated package at pypi. Could you please confirm that it's working?

**Comment by adambielski** [comment]
I renamed it before in my copy and of the repo and it worked, so I assume what you did should work as well :)

**Comment by podgorskiy** [comment]
Thanks!
